### ISSUE TITLE
Starship class

### ISSUE THREAD

**Issue by slithy** [slithy/bbw-traveller#1]
First things first: create a new data type "class Starship" which can hold all the data for a starship and its crew.

The initial version should contain the data items listed in the Starships chapter of the Core Rulebook, such as M-Drive, J-Drive, Power Plant, Fuel capacity, Cargo capacity, Staterooms, Cold Berths, etc.

Create commands to create a starship and show the stats of the starship.

Create a "save" and "load" command to save the Starship to a JSON file (like Bambleweeny Characters).

As we add additional functionality, the Starship can track things like contents of its cargo bay, remaining fuel, details of crew members, etc. but this does not need to be in the initial version.

**Comment by cattabiani** [comment]
ok, I need the manual. It will take some days but I would like to take this task. If you use the container, I will also try to use it this time. This will also slow me down a little probably

EDIT: I forgot that I can get the PDF faster. It will still take some time. I just came back from Italy

**Comment by slithy** [comment]
To run in the container:

* Register the application on https://discord.com/developers/applications and get a `DISCORD_BOT_TOKEN`

On a Linux system (I use Debian but any distro should be OK):
* Install `docker-compose` package
* `git clone git@github.com:slithy/bbw-traveller.git`
* Create a file `docker/env` which sets the following environment variables:
```
DISCORD_OWNER_USER_ID=
DISCORD_BOT_TOKEN=
MONGO_URL=mongodb://root:topsecret@mongo:27017
REDIS_URL=redis://redis:6379/0
```

* Create a file `cogst5/library_data.py` and add it to `.gitignore`. Contents of this file:
```
LibraryData = {
"dummy": "Dummy library data entry"
}
```
* In the top-level directory, type `make`. This should build and run the containers.
* If that works OK, create a new Discord server for testing and authorise this bot to run on the server.

Let me know if you have any problems.

**Comment by slithy** [comment]
To start with, `class Starship` should have the following members:

* name (string)
* type (string)
* TL (int)
* hull (int)
* is_streamlined (bool)
* armour (int)
* m_drive (int)
* j_drive (int)
* power_plant (int)
* fuel_capacity (int)
* fuel_jump (int)
* fuel_operations (int)
* has_fuel_scoop (bool)
* fuel_current (int)
* computer (int)
* computer_bis (bool)
* sensors (int)
* staterooms (int)
* low_berths (int)
* cargo_capacity (int)

with methods to set those values and display the starship summary

and methods to load/save

Once that is done we can add more features

**Comment by cattabiani** [comment]
I think I am almost there. However, I get this error:

```mongo-express_1  | Server is open to allow connections from anyone (0.0.0.0)
mongo-express_1  | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
bot_1            | INFO:disnake.client: logging in using static token
bot_1            | INFO:utils.clustering: Acquired lock with value '01f48b70-adc0-49ed-9d36-570278e7f8d5', coordinating shards!
bot_1            | INFO:bot: I am cluster 0.
bot_1            | INFO:utils.clustering: Coordination complete, releasing lock.
bot_1            | INFO:utils.clustering: Bucket 0 is available, launching shard ID 0
bot_1            | INFO:disnake.gateway: Shard ID 0 has sent the IDENTIFY payload.
bot_1            | INFO:bot: Launched 1 shards!
bot_1            | INFO:disnake.gateway: Websocket closed with 4014, cannot reconnect.
bot_1            | INFO:disnake.client: Cleaning up tasks.
bot_1            | INFO:disnake.client: Cleaning up after 3 tasks.
bot_1            | INFO:disnake.client: All tasks finished cancelling.
bot_1            | INFO:disnake.client: Closing the event loop.
bot_1            | Traceback (most recent call last):
bot_1            |   File "/home/bambleweeny/dbot.py", line 376, in <module>
bot_1            |     bot.run(config.TOKEN)
bot_1            |   File "/home/bambleweeny/.local/lib/python3.10/site-packages/disnake/client.py", line 856, in run
bot_1            |     return future.result()
bot_1            |   File "/home/bambleweeny/.local/lib/python3.10/site-packages/disnake/client.py", line 835, in runner
bot_1            |     await self.start(*args, **kwargs)
bot_1            |   File "/home/bambleweeny/.local/lib/python3.10/site-packages/disnake/client.py", line 799, in start
bot_1            |     await self.connect(reconnect=reconnect)
bot_1            |   File "/home/bambleweeny/.local/lib/python3.10/site-packages/disnake/shard.py", line 465, in connect
bot_1            |     await self.close()
bot_1            |   File "/home/bambleweeny/dbot.py", line 204, in close
bot_1            |     await self.ddb.close()
bot_1            | AttributeError: 'Avrae' object has no attribute 'ddb'. Did you mean: 'mdb'?
```

I think the real problem is that I cannot connect to the server, this line:
```
bot_1            | INFO:disnake.gateway: Websocket closed with 4014, cannot reconnect.
```

Did you already see this problem?

**Comment by cattabiani** [comment]
btw, I think `library_data.py` should be a `json` or `yaml` file

**Comment by slithy** [comment]
Error 4014 means that the app is not configured correctly in the Discord developer portal. See this page in the docs: https://discord.com/developers/docs/topics/gateway

**Comment by slithy** [comment]
> btw, I think `library_data.py` should be a `json` or `yaml` file

Having it hard-coded is quite a bit faster than reading it from a file in JSON format when the bot starts.

This data is not modified within Discord, so it never has to be saved. I don't see much advantage to having it as JSON.

**Comment by cattabiani** [comment]
the advantage is that if we need to add more data we can add another .json file and add a .gitignore rule for *.yaml

**Comment by cattabiani** [comment]
I have found (without reading) the files `ld.py`. `ld2.py` and `ld3.py`. They look like they contain library data. Can I read them?

**Comment by slithy** [comment]
> I have found (without reading) the files `ld.py`. `ld2.py` and `ld3.py`. They look like they contain library data. Can I read them?

Sorry, it was my mistake. Those were the source files that I used to generate the initial library data. I have removed them from the repo and rewritten history. Please rebase your local repo.

**Comment by slithy** [comment]
Some further thoughts: 

>     * fuel_current (int)

`fuel_current` should be a float. e.g. if it takes 1 ton of fuel for 4 weeks' operation, we should reduce fuel by 1/28 for every day that passes.

**Comment by cattabiani** [comment]
Also cargo capacity. I will make it so that it is easy to change in case we need

**Comment by cattabiani** [comment]
since I am still weighting for the book may I have a small description of each entry that you mentioned so that I know what we want to do with them? For example, `j_drive`: I do not know if it is just a value like `TL` or it carries some kind of logic like, for example, fuel

**Comment by slithy** [comment]
* name, type, TL, hull, - just for info
* is_streamlined - determines if you can enter a planetary atmosphere. Otherwise you can only use a highport and need a shuttle to go to planet's surface. Also required for skimming fuel from a gas giant.
* armour - subtracted from damage in space combat
* power_plant - normally just for info but can suffer damage in space combat causing ship systems to go offline
* m_drive - determines transit time between Jump point, gas giant, planetary orbit, landing on surface, etc. The formula is time = 2*sqrt(distance/acceleration). Units seconds, Km, M-drive rating.
* j_drive - determines maximum jump distance
* computer (int) - determines how many programs can run simultaneously on the computer. You could have an dict of available programs, each one of which is a skill and has a bandwidth rating (e.g. "Fire control/1" has a bandwidth of 5 and has the skill of Gunner-1 (or +1 to your Traveller gunner). The total bandwidth of running programs cannot exceed the computer rating, but you can have as many programs as you like which are not running.
* computer_bis (bool) - Computer is specialised for Jump-drive operations. Computer/5bis means computer 5 for most software programs but is rated 10 for Jump drive software.
* sensors (int) - bonus or penalty to be applied when using ship's sensors
* staterooms (int) - determines maximum capacity for crew/passengers.
* low_berths (int) - determines number of passengers who can take Low Passage
* cargo_capacity (int) - cargo bay capacity, see inventory thread

**Refuelling**

* fuel_capacity is maximum fuel tank capacity. fuel_jump is fuel consumed for a Jump-1 (multiply by 2 for a Jump-2). fuel_operations is how much fuel the ship consumes in 28 days of normal operations. fuel_current is how much fuel is in your fuel tank currently.
* has_fuel_scoop determines whether you can get fuel from a gas giant, but is says streamlining includes fuel scoops, so no need to record this separately. But num_fuel_processors would be useful to record. Each fuel processor can convert unrefined fuel into refined fuel at a rate of 20 tons/day.
* Actually fuel_jump is just 10% of the hull capacity (400 ton hull = 40 tons of fuel for a Jump-1) so not necessary to store this value separately
* For simplicity, subtract 1/28th of fuel_operations from fuel_current every day.
* Subtract fuel_jump*jump distance every time the ship jumps.
* Refuelling at a gas giant is free. At a class A or B starport, refined fuel is Cr.500/ton. At a class C or D starport, unrefined fuel costs Cr.100/ton.
* Refuelling takes 1D6 hours.
* Refuelling at a gas giant is a Difficult(10+) pilot check (1D6 hours)
* Refining hydrogen from gas giants or water from planets or unrefined fuel from class C/D starports can only be done by ships with a fuel refinery on board (is_streamlined = true).
* Using unrefined fuel when jumping is possible but dangerous (-2 penalty to Jump drive check)
* It would be useful to record refined and unrefined fuel separately.

**Comment by cattabiani** [comment]
I will try to implement everything thx. I do not understand the refined/unrefined fuel. Do we have 2 separate tanks? Don't they mix if we put them together in the same tank? Because otherwise I could just have a bool to mark it as refined or unrefined

**Comment by slithy** [comment]
The book doesn't explain in detail how it works. There are 2 tanks (one on port and one on starboard). I guess in most cases a bool is enough, when you "!refine_fuel" you just need to set is_refined = true and increment the calendar by 1 day per (20*num_fuel_processors) tons of fuel in the tanks.

**Comment by slithy** [comment]
There is a mistake in the formula for M-drive calculations. The book says time = 2*sqrt(distance/acceleration) but from the examples in the tables it's clear that this is a typo. It should be `time_in_secs = 20*sqrt(distance_in_km / acceleration_in_g)`

**Comment by slithy** [comment]
**Distances to use for M-drive calculations**

* Distance world surface to orbit is on average around 10,000 Km
* Distance world surface to a moon is on average around 400,000 Km
* Distance between worlds within the same system is typically 45-255 million Km
* Distance from world to gas giant is typically 600-900 million Km
* Distance from world to Jump distance = planetary diameter * 100 as mentioned above
* When jumping into a system, how close the ship arrives to the mainworld is a function of the Jump drive check. An effect of 6+ (exceptional success) is exactly at the optimal jump distance. Effect 1-5 (average success) is within 10% of optimal. Effect 0 (marginal success) is close but out by up to 10-60%. Effect -1 (marginal failure) causes a relativity error (adds 1D days to time in Jump space). Effect -2 (average failure) is a misjump, arrive in the target system at a distance of 100-600% of optimal. Worse than -2 is a catastrophic misjump, you end up in the wrong system or in empty space.

**J-drive calculations**

* Easy (4+) Astrogation + EDU check (1D x 10 minutes), modified by the Jump distance (-1 DM per parsec). Failures can be retried.
* Easy (4+) Engineer (J-Drive) + EDU check (1D x 10 minutes) modified by the effect of the Astrogation check. -1 DM per month if annual maintenance was not carried out. -2 DM if using unrefined fuel. -4 DM if still within the 100-diameter limit.
* Time in Jump space is 148 + 6D hours, regardless of distance.

**Comment by cattabiani** [comment]
The hull is just the size of the ship?

**Comment by slithy** [comment]
> The hull is just the size of the ship?

Yes. When constructing a starship, everything in the ship, from staterooms to fuel tanks, has a volume and it all has to fit within the hull. The hull value is used to calculate how much fuel is needed to Jump.

**Comment by cattabiani** [comment]
double checking the equations it is clear that there was a typo but not the one you are suggesting. The formula should be:

t = sqrt(2*d/a) where d is in meters and a is in meters/s^2 (1G is approximated to 10 m/s^2). They are clearly using the formula for constant acceleration. Integrating a in time twice we get the distance. I verified with the examples and I fit them perfectly, all the decimal digits.

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
